# Generated by Django 5.0.7 on 2024-11-02 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=50)),
                ('data', models.JSONField()),
                ('isAvailable', models.BooleanField(default=True)),
                ('date', models.DateField(default=datetime.date(2024, 11, 2))),
            ],
        ),
    ]
