# Generated by Django 5.0.7 on 2024-11-14 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='image',
            field=models.ImageField(default='food_img/default.jpg', upload_to='food_img/'),
        ),
        migrations.AlterField(
            model_name='additem',
            name='date',
            field=models.DateField(default=datetime.date(2024, 11, 14)),
        ),
    ]
