# Generated by Django 5.0.7 on 2024-11-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_additem_image_alter_additem_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddItem',
            new_name='FoodItems',
        ),
    ]
