# Generated by Django 5.0.7 on 2024-11-28 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0004_alter_fooditems_date_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Food', models.JSONField()),
                ('cost', models.FloatField()),
                ('status', models.IntegerField(default=1)),
                ('isCompleted', models.BooleanField(default=False)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to='hotelapp.userdetails')),
            ],
        ),
    ]
