# Generated by Django 5.0.7 on 2024-11-28 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0005_fooditems_count_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='instruction',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orders',
            name='pick_up_time',
            field=models.TimeField(blank=True, default=datetime.time(14, 2, 1, 225211)),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
